name: Primer Workflow

on:
 push:
   branches: [main]
 pull_request:
   branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    env:
      API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Build and Test with Maven
        run: mvn clean verify